### ISSUE TITLE
Implement Functionality To Display Store Items

### ISSUE THREAD

**Issue by dylanfernandes** [dylanfernandes/educanimour#3]
## Task Description
Users will be able to see information on items present in the store.

## Task Breakdown
- [ ] Create test store items in Express
- [ ] Implement design with Angular
- [ ] Replace test data with data from MongoDB
