### ISSUE TITLE
Implement Functionality To Add Store Items for Admin

### ISSUE THREAD

**Issue by dylanfernandes** [dylanfernandes/educanimour#4]
## Task Description
Admin will be able to insert items into the store from the admin page.

## Task Breakdown
- [ ] Set up MongoDB for insertion (connect + create tables)
- [ ] Implement logic for data insertion
- [ ] Implement design for data insertion with Angular
