### ISSUE TITLE
Create Admin Page

### ISSUE THREAD

**Issue by dylanfernandes** [dylanfernandes/educanimour#5]
## Task Description
Admin will have access to admin privileges through admin page.

## Task Breakdown
- [ ] Protect page access with password
- [ ] Implement design with Angular
- [ ] Add admin functionalities created to page
